version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: qa_platform_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/qa_platform_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    command: bundle exec rails server -b 0.0.0.0 -p 3001

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0

volumes:
  postgres_data: