[phases.setup]
nixPkgs = ['nodejs', 'ruby_3_2', 'postgresql']

[phases.install]
cmds = ['cd backend && bundle install']

[phases.build]
cmds = ['cd backend && bundle exec rails assets:precompile']

[start]
cmd = 'cd backend && bundle exec rails server -p $PORT -e production'