[phases.setup]
nixPkgs = ["nodejs", "ruby_3_2", "postgresql", "gcc", "gnumake", "pkg-config", "libyaml"]

[phases.install]
cmds = ["cd backend && bundle install"]

[phases.build]
cmds = ["cd backend && bundle exec rails assets:precompile"]

[start]
cmd = "cd backend && bundle exec rails server -b 0.0.0.0 -p $PORT"