services:
  - type: web
    name: qa-platform-frontend
    env: static
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html