source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 7.1.0"
gem "pg", "~> 1.1", group: :production
gem "sqlite3", "~> 1.4", group: [:development, :test]
gem "puma", ">= 5.0"
gem "bootsnap", require: false
gem "rack-cors"
gem "jbuilder"
gem "jwt"
gem "bcrypt"
gem "psych", "~> 4.0"
gem "dotenv-rails", groups: [:development, :test]