version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: qa_platform_production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ../backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/qa_platform_production
      RAILS_ENV: production
    depends_on:
      - db

volumes:
  postgres_data: